### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by yqnjuee** [guanpengchn/awesome-books#2]
There are three books can't download via your link.
Click links below to check this issue.

https://github.com/guanpengchn/awesome-books/raw/master/%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/%E5%88%86%E5%B8%83%E5%BC%8F%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84%EF%BC%9A%E5%8E%9F%E7%90%86%E3%80%81%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E6%88%98.pdf

https://github.com/guanpengchn/awesome-books/raw/master/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E7%AB%9E%E8%B5%9B%E5%85%A5%E9%97%A8%E7%BB%8F%E5%85%B8%EF%BC%88%E7%AC%AC2%E7%89%88%EF%BC%89.pdf

https://github.com/guanpengchn/awesome-books/raw/master/%E5%89%8D%E7%AB%AF/CSS%E6%8F%AD%E7%A7%98.pdf

有三本书下不了，点击上面的链接查看分别是哪三本，谢谢

**Comment by guanpengchn** [comment]
感谢反馈，我晚上处理下

**Comment by guanpengchn** [comment]
第一个链接由于文件过大，所以分成了四部分，没办法一次性下载完毕，现在在readme中修改到了该文件的地址，https://github.com/guanpengchn/awesome-books/tree/master/%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/%E5%88%86%E5%B8%83%E5%BC%8F%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84%EF%BC%9A%E5%8E%9F%E7%90%86%E3%80%81%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E6%88%98

需要手动下载

第二本和第三本书由于命名出错，已经修复
