### ISSUE TITLE
书名中有冒号，无法clone下来

### ISSUE THREAD

**Issue by zhangmx** [guanpengchn/awesome-books#3]
https://github.com/guanpengchn/awesome-books/blob/master/%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/Hadoop:%20The%20Definitive%20Guide%20MapReduce%20for%20the%20Cloud.pdf

这本 hadoop的书名有冒号，windows下clone后，只剩hadoop了

**Comment by zhangmx** [comment]
还有 图解TCP&IP : 第5版.pdf 这本

**Comment by idongliming** [comment]
直接下载就好了呀，可以单独下载一个文件的。clone下来体积是好几倍没有什么意义

**Comment by guanpengchn** [comment]
@zhangmx 我哪天改个名，这两本你先单独下载吧

**Comment by zhangmx** [comment]
@guanpengchn @idongliming 🙏感谢回复。下载的确没问题的，其实原因在windows的文件命名中不能有特殊符号。直接下载后都被自动替换成下划线了。只是发现了一下这个小问题，我去看书啦（习惯了打劫式下载电子书了，看到电子书的仓库都是浅clone下来，担心哪天仓库不见了）

**Comment by guanpengchn** [comment]
@zhangmx 好的好的，我之后注意哈哈
