### ISSUE TITLE
书籍都不可以下载了，怎么回事？

### ISSUE THREAD

**Issue by lxiaodie** [guanpengchn/awesome-books#4]

**Comment by guanpengchn** [comment]
是不是又被墙了

**Comment by KF-Liang** [comment]
不行啊

**Comment by edte** [comment]
挂代理了没，这么大，直接 clone 比较难受，一失败就全没了，我是找自己需要的，经典的书单 clone，因为 star 了好多个，有很多重复的，有些版本也不一样。都存了好多 g 了，还没看完几本。。

**Comment by guanpengchn** [comment]
@edte 用什么下什么吧，fork了也行
